### PR TITLE
Benchmarking plugin

### LINKED ISSUE #53: Use repo owners instead of OWNERS file to verify permissions for running benchmarks.
It would be much easier to just check if the commenter is also a repo owner instead of maintaining a separate file.

### PR DESCRIPTION
**Pull request by krasi-georgiev**
added just the benchmarking and the second commit is to simplify the checking to allow any org member to trigger a benchmark.

fixes: https://github.com/prometheus/prombench/issues/53

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
ping @sipian

**Comment by sipian** [comment]
I had commented out a few lines in [plank](https://github.com/sipian/test-infra/blob/prometheus-prow/prow/report/report.go#L240) too

**Comment by krasi-georgiev** [comment]
lets add this in a separate PR if it is important

**Comment by sipian** [comment]
lgtm

**Pull request merged**
